spring:
  application:
    name: PAYMENT-SERVICE
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:testdb

  
server:
  port: 9191

management:
  tracing:
    sampling:
      probability : 1.0
      